In [4]:
!jupyter nbconvert --to=html 100_numpy_intro.ipynb

[NbConvertApp] WARNING | pattern '100_numpy_intro.ipynb' matched no files
This application is used to convert notebook files (*.ipynb)
        to various other formats.


Options
The options below are convenience aliases to configurable class-options,
as listed in the "Equivalent to" description-line of the aliases.
To see all configurable class-options for some <cmd>, use:
    <cmd> --help-all

--debug
    set log level to logging.DEBUG (maximize logging output)
    Equivalent to: [--Application.log_level=10]
--show-config
    Show the application's configuration (human-readable format)
    Equivalent to: [--Application.show_config=True]
--show-config-json
    Show the application's configuration (json format)
    Equivalent to: [--Application.show_config_json=True]
--generate-config
    generate default config file
    Equivalent to: [--JupyterApp.generate_config=True]
-y
    Answer yes to any questions instead of prompting.
    Equivalent to: [--JupyterApp.answer_yes=True]
--execute

# Numpy Intro

Figures taken from L. Maximov's Numpy tutorial
https://betterprogramming.pub/numpy-illustrated-the-visual-guide-to-numpy-3b1d4976de1d

In [1]:
import numpy as np

__________________________________________________________________
## Array generation
![image info](https://miro.medium.com/v2/resize:fit:1100/format:webp/1*cyN_FxUVbkdDyrULhfTIGw.png)

[zeros](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html)
[zeros_like](https://numpy.org/doc/stable/reference/generated/numpy.zeros_like.html)

[ones](https://numpy.org/doc/stable/reference/generated/numpy.ones.html)
[ones_like](https://numpy.org/doc/stable/reference/generated/numpy.ones_like.html)

In [2]:
a = np.array([1,2,3])
np.ones_like(a)

array([1, 1, 1])

![image info](https://miro.medium.com/v2/resize:fit:1100/format:webp/1*NNCWBPDCPfLtNYDc_ul5SA.png)

[arange](https://numpy.org/doc/stable/reference/generated/numpy.arange.html)
[linspace](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html)

In [3]:
np.arange(5)

array([0, 1, 2, 3, 4])

__________________________________________________________________
## Array math operations
![image info](https://miro.medium.com/v2/resize:fit:1100/format:webp/1*RNfQubSwH_6-GnWHVjn9CQ.png)

### Broadcasting
![image info](https://miro.medium.com/v2/resize:fit:1100/format:webp/1*VyadDu7CyuF5-7rKVoFSrw.png)

[built-in operators](https://docs.python.org/3/library/operator.html)

In [4]:
a = np.arange(3)
a + 3

array([3, 4, 5])

__________________________________________________________________
## Math operations
![image info](https://miro.medium.com/v2/resize:fit:1100/format:webp/1*Pc4t0jilbHSM0sMwtVNGIA.png)
![image info](https://miro.medium.com/v2/resize:fit:1100/format:webp/1*wyHVvsoUdsHA0RedM6kdvQ.png)

[sqrt](https://numpy.org/doc/stable/reference/generated/numpy.sqrt.html)
[exp](https://numpy.org/doc/stable/reference/generated/numpy.exp.html)
[log](https://numpy.org/doc/stable/reference/generated/numpy.log.html)

[sin](https://numpy.org/doc/stable/reference/generated/numpy.sin.html)
[cos](https://numpy.org/doc/stable/reference/generated/numpy.cos.html)
[arctan2](https://numpy.org/doc/stable/reference/generated/numpy.arctan2.html)

In [17]:
a = np.arange(6)
a**2

array([ 0,  1,  4,  9, 16, 25])

__________________________________________________________________
## Indexing I
![image info](https://miro.medium.com/v2/resize:fit:4800/format:webp/1*4xpufyWZWcIbabsOHVlc4g.png)

In [5]:
a = np.arange(1,6)
a[[1,-1]]

array([2, 5])

### Boolean indexing

![image info](https://miro.medium.com/v2/resize:fit:1100/format:webp/1*nFGcXav_xxD7TXGiRYMpHg.png)

In [8]:
a = 7-np.abs(np.arange(13) - 6)
print(a)
a > 5

[1 2 3 4 5 6 7 6 5 4 3 2 1]


array([False, False, False, False, False,  True,  True,  True, False,
       False, False, False, False])

In [ ]:
#Exercise
#Consider a single-cycle sine wave, u, in spatial coordinates as initial condition for a pressure field, 
#from which the first spatial derivative is to be computed by means of a finite-difference expression. 
#
#a) Write a script that calculates and displays the derivative of u. 
#b) Compare the numerical solution with the analytical solution.

import numpy as np
from matplotlib import pyplot as plt
#Basic parameters
#---------------------------------------------------------------
nx = 100      # number of grid points in x
dx = 0.1     # grid point distance in m
x_vec = np.arange(0, nx)*dx  # initialize space coordinates
_lambda = 10.0  # wavelength, happens to be nx*dx
k = 2*np.pi/_lambda  # wavenumber
u = np.sin(k*x_vec)  #signal

dudx = np.zeros(nx) #initialize derivative

#FD routine
#may be you want to try a for loop (another option may be np.diff)
for i in range(len(u)):
    dudx[i] = ...

# analytical solution for du/dx
dudx_an = ... 

#plotting
fig = plt.figure(figsize=(5,5))
ax1 = fig.add_subplot(1,2,1)

ax1.plot(x_vec, u, color=3*[0], label='u')
ax1.plot(x_vec, dudx_an, '--k', label='dudx_analytic')
ax1.plot(x_vec, dudx, '-r', label='dudx')
ax1.set_xlabel('x (m)')
ax1.set_ylabel('u ()')
ax1.legend()

_____________________________________________________
# "Going beyond vectors"
____________________________________________________

In [9]:
def demo_array(dim: tuple, verbose = True):
    dim = dim
    matrix = np.zeros(dim)

    for idcs,_ in np.ndenumerate(matrix):
        matrix[idcs] = np.sum(idcs)

    if verbose:
        print(matrix)
        
    return matrix

a = demo_array((3,3))

[[0. 1. 2.]
 [1. 2. 3.]
 [2. 3. 4.]]


## Matrix arrays
![image info](https://miro.medium.com/v2/resize:fit:1100/format:webp/1*aLMuXA81pDXaw0J0QdKvRQ.png)

![image info](https://miro.medium.com/v2/resize:fit:720/format:webp/1*jmXqsVUNaBaUsBAkHgqb3A.png)

[sum](https://numpy.org/doc/stable/reference/generated/numpy.sum.html)
[median](https://numpy.org/doc/stable/reference/generated/numpy.median.html)
[mean](https://numpy.org/doc/stable/reference/generated/numpy.mean.html)

In [10]:
a = demo_array((3,3))
a.sum

[[0. 1. 2.]
 [1. 2. 3.]
 [2. 3. 4.]]


<function ndarray.sum>

__________________________________________________________________
## Indexing II
![image info](https://miro.medium.com/v2/resize:fit:4800/format:webp/1*brbsl7QFZGWfmvgFHMwt9Q.png)

In [24]:
a = demo_array((3,4))
a[:]

[[0. 1. 2. 3.]
 [1. 2. 3. 4.]
 [2. 3. 4. 5.]]


array([[0., 1., 2., 3.],
       [1., 2., 3., 4.],
       [2., 3., 4., 5.]])

__________________________________________________________________
## Higher-dimensional arrays
![image info](https://miro.medium.com/v2/resize:fit:1100/format:webp/1*BAr1RXkpGJD5lcwbTePGLA.png)

[ndim](https://numpy.org/doc/stable/reference/generated/numpy.ndim.html)
[shape](https://numpy.org/doc/stable/reference/generated/numpy.shape.html)
[size](https://numpy.org/doc/stable/reference/generated/numpy.size.html)

In [12]:
a = demo_array((3,2,4))
a.size

[[[0. 1. 2. 3.]
  [1. 2. 3. 4.]]

 [[1. 2. 3. 4.]
  [2. 3. 4. 5.]]

 [[2. 3. 4. 5.]
  [3. 4. 5. 6.]]]


24

__________________________________________________________________
__________________________________________________________________
__________________________________________________________________
## Further array operations

![image info](https://miro.medium.com/v2/resize:fit:1100/format:webp/1*bUfuXiTZOas6ZSD_lOSbXA.png)

[stack](https://numpy.org/doc/stable/reference/generated/numpy.stack.html)

![image info](https://miro.medium.com/v2/resize:fit:1100/format:webp/1*EJiDVb9xb8VL9XmFDevSGg.png)

[swapaxes](https://numpy.org/doc/stable/reference/generated/numpy.swapaxes.html)